[cardinal]
BASE_SHARD_SEQUENCER_ADDRESS = ''
CARDINAL_LOG_LEVEL = 'info'
CARDINAL_MODE = 'development'
CARDINAL_NAMESPACE = 'my-world-1'
REDIS_ADDRESS = ''
REDIS_PASSWORD = ''

[common]
ROUTER_KEY = '30f493e7c3263e9d645e149e90419fcb9f386172fe167b92d2e7202a56244392'

[evm]
BLOCK_TIME = '1s'
CHAIN_ID = 'world-engine'
DA_AUTH_TOKEN = ''
DA_BASE_URL = 'http://celestia-devnet:26658'
DA_NAMESPACE_ID = '67480c4a88c4d12935d4'
FAUCET_ADDR = 'world142fg37yzx04cslgeflezzh83wa4xlmjpms0sg5'
KEY_MNEMONIC = 'enact adjust liberty squirrel bulk ticket invest tissue antique window thank slam unknown fury script among bread social switch glide wool clog flag enroll'

[nakama]
ENABLE_ALLOWLIST = 'false'
OUTGOING_QUEUE_SIZE = 64
